[project]
name = 'time_locked_wallet'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.time-locked-wallet]
path = 'contracts/time-locked-wallet.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
